#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamarinDroidCustomListView.Resource", IsApplication=true)]

namespace XamarinDroidCustomListView
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int gray = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_selector = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080016
			public const int action_add_services = 2131230742;
			
			// aapt resource value: 0x7f08000e
			public const int buttonCategory = 2131230734;
			
			// aapt resource value: 0x7f080013
			public const int buttonDeleteService = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int buttonEditService = 2131230738;
			
			// aapt resource value: 0x7f08000b
			public const int checkBoxAddCategory = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int editTextAddCategory = 2131230733;
			
			// aapt resource value: 0x7f080006
			public const int editTextDescription = 2131230726;
			
			// aapt resource value: 0x7f080004
			public const int editTextName = 2131230724;
			
			// aapt resource value: 0x7f080008
			public const int editTextPrice = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout1 = 2131230729;
			
			// aapt resource value: 0x7f08000c
			public const int linearLayoutCategorySection = 2131230732;
			
			// aapt resource value: 0x7f080001
			public const int linearLayoutContainer = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int scrollView1 = 2131230720;
			
			// aapt resource value: 0x7f080014
			public const int service_list = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int service_list_empty = 2131230741;
			
			// aapt resource value: 0x7f08000a
			public const int spinnerCategory = 2131230730;
			
			// aapt resource value: 0x7f080002
			public const int textTitle = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int textViewDescription = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int textViewName = 2131230723;
			
			// aapt resource value: 0x7f080007
			public const int textViewPrice = 2131230727;
			
			// aapt resource value: 0x7f080010
			public const int tvServiceCategory = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int tvServiceName = 2131230735;
			
			// aapt resource value: 0x7f080011
			public const int tvServicePrice = 2131230737;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AddServiceDialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int CustomRow = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int ServiceMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int add_service_item = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int no_services = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int DividerStyle = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int LabelStyle = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
